/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as legalRouteRouteImport } from './routes/(legal)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as V1SplatRouteImport } from './routes/v1/$'
import { Route as marketingPricingRouteImport } from './routes/(marketing)/pricing'
import { Route as legalTermsRouteImport } from './routes/(legal)/terms'
import { Route as legalSecurityRouteImport } from './routes/(legal)/security'
import { Route as legalPrivacyRouteImport } from './routes/(legal)/privacy'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOnboardingRouteImport } from './routes/(auth)/onboarding'
import { Route as appKeysRouteImport } from './routes/(app)/keys'
import { Route as appHelpRouteImport } from './routes/(app)/help'
import { Route as appDashboardRouteImport } from './routes/(app)/dashboard'
import { Route as appConnectionsRouteImport } from './routes/(app)/connections'
import { Route as appSettingsRouteRouteImport } from './routes/(app)/settings/route'
import { Route as appSettingsIndexRouteImport } from './routes/(app)/settings/index'
import { Route as appPostsIndexRouteImport } from './routes/(app)/posts/index'
import { Route as authInviteIdRouteImport } from './routes/(auth)/invite.$id'
import { Route as appSettingsOrganizationRouteImport } from './routes/(app)/settings/organization'
import { Route as appSettingsMembersRouteImport } from './routes/(app)/settings/members'
import { Route as appSettingsIntegrationsRouteImport } from './routes/(app)/settings/integrations'
import { Route as appSettingsCredentialsRouteImport } from './routes/(app)/settings/credentials'
import { Route as appSettingsBillingRouteImport } from './routes/(app)/settings/billing'
import { Route as appPostsCreateRouteImport } from './routes/(app)/posts/create'
import { Route as appKeysIdRouteImport } from './routes/(app)/keys.$id'

const legalRouteRoute = legalRouteRouteImport.update({
  id: '/(legal)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SplatRoute = V1SplatRouteImport.update({
  id: '/v1/$',
  path: '/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingPricingRoute = marketingPricingRouteImport.update({
  id: '/(marketing)/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const legalTermsRoute = legalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => legalRouteRoute,
} as any)
const legalSecurityRoute = legalSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => legalRouteRoute,
} as any)
const legalPrivacyRoute = legalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => legalRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authOnboardingRoute = authOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => authRouteRoute,
} as any)
const appKeysRoute = appKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => appRouteRoute,
} as any)
const appHelpRoute = appHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => appRouteRoute,
} as any)
const appDashboardRoute = appDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appRouteRoute,
} as any)
const appConnectionsRoute = appConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsRouteRoute = appSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsIndexRoute = appSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appSettingsRouteRoute,
} as any)
const appPostsIndexRoute = appPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => appRouteRoute,
} as any)
const authInviteIdRoute = authInviteIdRouteImport.update({
  id: '/invite/$id',
  path: '/invite/$id',
  getParentRoute: () => authRouteRoute,
} as any)
const appSettingsOrganizationRoute = appSettingsOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => appSettingsRouteRoute,
} as any)
const appSettingsMembersRoute = appSettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => appSettingsRouteRoute,
} as any)
const appSettingsIntegrationsRoute = appSettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => appSettingsRouteRoute,
} as any)
const appSettingsCredentialsRoute = appSettingsCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => appSettingsRouteRoute,
} as any)
const appSettingsBillingRoute = appSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => appSettingsRouteRoute,
} as any)
const appPostsCreateRoute = appPostsCreateRouteImport.update({
  id: '/posts/create',
  path: '/posts/create',
  getParentRoute: () => appRouteRoute,
} as any)
const appKeysIdRoute = appKeysIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => appKeysRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof appSettingsRouteRouteWithChildren
  '/connections': typeof appConnectionsRoute
  '/dashboard': typeof appDashboardRoute
  '/help': typeof appHelpRoute
  '/keys': typeof appKeysRouteWithChildren
  '/onboarding': typeof authOnboardingRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/privacy': typeof legalPrivacyRoute
  '/security': typeof legalSecurityRoute
  '/terms': typeof legalTermsRoute
  '/pricing': typeof marketingPricingRoute
  '/v1/$': typeof V1SplatRoute
  '/keys/$id': typeof appKeysIdRoute
  '/posts/create': typeof appPostsCreateRoute
  '/settings/billing': typeof appSettingsBillingRoute
  '/settings/credentials': typeof appSettingsCredentialsRoute
  '/settings/integrations': typeof appSettingsIntegrationsRoute
  '/settings/members': typeof appSettingsMembersRoute
  '/settings/organization': typeof appSettingsOrganizationRoute
  '/invite/$id': typeof authInviteIdRoute
  '/posts/': typeof appPostsIndexRoute
  '/settings/': typeof appSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connections': typeof appConnectionsRoute
  '/dashboard': typeof appDashboardRoute
  '/help': typeof appHelpRoute
  '/keys': typeof appKeysRouteWithChildren
  '/onboarding': typeof authOnboardingRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/privacy': typeof legalPrivacyRoute
  '/security': typeof legalSecurityRoute
  '/terms': typeof legalTermsRoute
  '/pricing': typeof marketingPricingRoute
  '/v1/$': typeof V1SplatRoute
  '/keys/$id': typeof appKeysIdRoute
  '/posts/create': typeof appPostsCreateRoute
  '/settings/billing': typeof appSettingsBillingRoute
  '/settings/credentials': typeof appSettingsCredentialsRoute
  '/settings/integrations': typeof appSettingsIntegrationsRoute
  '/settings/members': typeof appSettingsMembersRoute
  '/settings/organization': typeof appSettingsOrganizationRoute
  '/invite/$id': typeof authInviteIdRoute
  '/posts': typeof appPostsIndexRoute
  '/settings': typeof appSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(legal)': typeof legalRouteRouteWithChildren
  '/(app)/settings': typeof appSettingsRouteRouteWithChildren
  '/(app)/connections': typeof appConnectionsRoute
  '/(app)/dashboard': typeof appDashboardRoute
  '/(app)/help': typeof appHelpRoute
  '/(app)/keys': typeof appKeysRouteWithChildren
  '/(auth)/onboarding': typeof authOnboardingRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(legal)/privacy': typeof legalPrivacyRoute
  '/(legal)/security': typeof legalSecurityRoute
  '/(legal)/terms': typeof legalTermsRoute
  '/(marketing)/pricing': typeof marketingPricingRoute
  '/v1/$': typeof V1SplatRoute
  '/(app)/keys/$id': typeof appKeysIdRoute
  '/(app)/posts/create': typeof appPostsCreateRoute
  '/(app)/settings/billing': typeof appSettingsBillingRoute
  '/(app)/settings/credentials': typeof appSettingsCredentialsRoute
  '/(app)/settings/integrations': typeof appSettingsIntegrationsRoute
  '/(app)/settings/members': typeof appSettingsMembersRoute
  '/(app)/settings/organization': typeof appSettingsOrganizationRoute
  '/(auth)/invite/$id': typeof authInviteIdRoute
  '/(app)/posts/': typeof appPostsIndexRoute
  '/(app)/settings/': typeof appSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/connections'
    | '/dashboard'
    | '/help'
    | '/keys'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/pricing'
    | '/v1/$'
    | '/keys/$id'
    | '/posts/create'
    | '/settings/billing'
    | '/settings/credentials'
    | '/settings/integrations'
    | '/settings/members'
    | '/settings/organization'
    | '/invite/$id'
    | '/posts/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connections'
    | '/dashboard'
    | '/help'
    | '/keys'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/pricing'
    | '/v1/$'
    | '/keys/$id'
    | '/posts/create'
    | '/settings/billing'
    | '/settings/credentials'
    | '/settings/integrations'
    | '/settings/members'
    | '/settings/organization'
    | '/invite/$id'
    | '/posts'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(auth)'
    | '/(legal)'
    | '/(app)/settings'
    | '/(app)/connections'
    | '/(app)/dashboard'
    | '/(app)/help'
    | '/(app)/keys'
    | '/(auth)/onboarding'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(legal)/privacy'
    | '/(legal)/security'
    | '/(legal)/terms'
    | '/(marketing)/pricing'
    | '/v1/$'
    | '/(app)/keys/$id'
    | '/(app)/posts/create'
    | '/(app)/settings/billing'
    | '/(app)/settings/credentials'
    | '/(app)/settings/integrations'
    | '/(app)/settings/members'
    | '/(app)/settings/organization'
    | '/(auth)/invite/$id'
    | '/(app)/posts/'
    | '/(app)/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  legalRouteRoute: typeof legalRouteRouteWithChildren
  marketingPricingRoute: typeof marketingPricingRoute
  V1SplatRoute: typeof V1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(legal)': {
      id: '/(legal)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof legalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/$': {
      id: '/v1/$'
      path: '/v1/$'
      fullPath: '/v1/$'
      preLoaderRoute: typeof V1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/pricing': {
      id: '/(marketing)/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof marketingPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legal)/terms': {
      id: '/(legal)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof legalTermsRouteImport
      parentRoute: typeof legalRouteRoute
    }
    '/(legal)/security': {
      id: '/(legal)/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof legalSecurityRouteImport
      parentRoute: typeof legalRouteRoute
    }
    '/(legal)/privacy': {
      id: '/(legal)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof legalPrivacyRouteImport
      parentRoute: typeof legalRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/onboarding': {
      id: '/(auth)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof authOnboardingRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/keys': {
      id: '/(app)/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof appKeysRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/help': {
      id: '/(app)/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof appHelpRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/connections': {
      id: '/(app)/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof appConnectionsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/': {
      id: '/(app)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof appSettingsIndexRouteImport
      parentRoute: typeof appSettingsRouteRoute
    }
    '/(app)/posts/': {
      id: '/(app)/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof appPostsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/invite/$id': {
      id: '/(auth)/invite/$id'
      path: '/invite/$id'
      fullPath: '/invite/$id'
      preLoaderRoute: typeof authInviteIdRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/settings/organization': {
      id: '/(app)/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof appSettingsOrganizationRouteImport
      parentRoute: typeof appSettingsRouteRoute
    }
    '/(app)/settings/members': {
      id: '/(app)/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof appSettingsMembersRouteImport
      parentRoute: typeof appSettingsRouteRoute
    }
    '/(app)/settings/integrations': {
      id: '/(app)/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof appSettingsIntegrationsRouteImport
      parentRoute: typeof appSettingsRouteRoute
    }
    '/(app)/settings/credentials': {
      id: '/(app)/settings/credentials'
      path: '/credentials'
      fullPath: '/settings/credentials'
      preLoaderRoute: typeof appSettingsCredentialsRouteImport
      parentRoute: typeof appSettingsRouteRoute
    }
    '/(app)/settings/billing': {
      id: '/(app)/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof appSettingsBillingRouteImport
      parentRoute: typeof appSettingsRouteRoute
    }
    '/(app)/posts/create': {
      id: '/(app)/posts/create'
      path: '/posts/create'
      fullPath: '/posts/create'
      preLoaderRoute: typeof appPostsCreateRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/keys/$id': {
      id: '/(app)/keys/$id'
      path: '/$id'
      fullPath: '/keys/$id'
      preLoaderRoute: typeof appKeysIdRouteImport
      parentRoute: typeof appKeysRoute
    }
  }
}

interface appSettingsRouteRouteChildren {
  appSettingsBillingRoute: typeof appSettingsBillingRoute
  appSettingsCredentialsRoute: typeof appSettingsCredentialsRoute
  appSettingsIntegrationsRoute: typeof appSettingsIntegrationsRoute
  appSettingsMembersRoute: typeof appSettingsMembersRoute
  appSettingsOrganizationRoute: typeof appSettingsOrganizationRoute
  appSettingsIndexRoute: typeof appSettingsIndexRoute
}

const appSettingsRouteRouteChildren: appSettingsRouteRouteChildren = {
  appSettingsBillingRoute: appSettingsBillingRoute,
  appSettingsCredentialsRoute: appSettingsCredentialsRoute,
  appSettingsIntegrationsRoute: appSettingsIntegrationsRoute,
  appSettingsMembersRoute: appSettingsMembersRoute,
  appSettingsOrganizationRoute: appSettingsOrganizationRoute,
  appSettingsIndexRoute: appSettingsIndexRoute,
}

const appSettingsRouteRouteWithChildren =
  appSettingsRouteRoute._addFileChildren(appSettingsRouteRouteChildren)

interface appKeysRouteChildren {
  appKeysIdRoute: typeof appKeysIdRoute
}

const appKeysRouteChildren: appKeysRouteChildren = {
  appKeysIdRoute: appKeysIdRoute,
}

const appKeysRouteWithChildren =
  appKeysRoute._addFileChildren(appKeysRouteChildren)

interface appRouteRouteChildren {
  appSettingsRouteRoute: typeof appSettingsRouteRouteWithChildren
  appConnectionsRoute: typeof appConnectionsRoute
  appDashboardRoute: typeof appDashboardRoute
  appHelpRoute: typeof appHelpRoute
  appKeysRoute: typeof appKeysRouteWithChildren
  appPostsCreateRoute: typeof appPostsCreateRoute
  appPostsIndexRoute: typeof appPostsIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appSettingsRouteRoute: appSettingsRouteRouteWithChildren,
  appConnectionsRoute: appConnectionsRoute,
  appDashboardRoute: appDashboardRoute,
  appHelpRoute: appHelpRoute,
  appKeysRoute: appKeysRouteWithChildren,
  appPostsCreateRoute: appPostsCreateRoute,
  appPostsIndexRoute: appPostsIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authOnboardingRoute: typeof authOnboardingRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  authInviteIdRoute: typeof authInviteIdRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authOnboardingRoute: authOnboardingRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  authInviteIdRoute: authInviteIdRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface legalRouteRouteChildren {
  legalPrivacyRoute: typeof legalPrivacyRoute
  legalSecurityRoute: typeof legalSecurityRoute
  legalTermsRoute: typeof legalTermsRoute
}

const legalRouteRouteChildren: legalRouteRouteChildren = {
  legalPrivacyRoute: legalPrivacyRoute,
  legalSecurityRoute: legalSecurityRoute,
  legalTermsRoute: legalTermsRoute,
}

const legalRouteRouteWithChildren = legalRouteRoute._addFileChildren(
  legalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  legalRouteRoute: legalRouteRouteWithChildren,
  marketingPricingRoute: marketingPricingRoute,
  V1SplatRoute: V1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
