// Logos
import {
	FacebookIcon,
	InstagramIcon,
	LinkedinIcon,
	XTwitterIcon,
	ThreadsIcon,
	TiktokIcon,
	BlueskyIcon,
	DiscordIcon,
	KuaishouIcon,
	MastodonIcon,
	MediumIcon,
	PinterestIcon,
	RedditIcon,
	SlackIcon,
	SnapchatIcon,
	TelegramIcon,
	TumblrIcon,
	VimeoIcon,
	YoutubeIcon,
} from "@/icons/logos";

export const platformDetails = {
	twitter: {
		supported: true,
		name: "X (Twitter)",
		logo: XTwitterIcon,
		color: "dark",
	},
	tiktok: {
		supported: process.env.NODE_ENV === "development",
		name: "TikTok",
		logo: TiktokIcon,
		color: "dark",
	},
	threads: {
		supported: true,
		name: "Threads",
		logo: ThreadsIcon,
		color: "dark",
	},
	instagram: {
		supported: true,
		name: "Instagram",
		logo: InstagramIcon,
		color: "pink",
	},
	facebook: {
		supported: true,
		name: "Facebook",
		logo: FacebookIcon,
		color: "blue",
	},
	linkedin: {
		supported: true,
		name: "LinkedIn",
		logo: LinkedinIcon,
		color: "blue",
	},
	google: {
		supported: true,
		name: "YouTube (Google)",
		logo: YoutubeIcon,
		color: "red",
	},
	bluesky: {
		supported: false,
		name: "Bluesky",
		logo: BlueskyIcon,
		color: "blue",
	},
	discord: {
		supported: false,
		name: "Discord",
		logo: DiscordIcon,
		color: "blue",
	},
	kuaishou: {
		supported: false,
		name: "Kuaishou",
		logo: KuaishouIcon,
		color: "dark",
	},
	mastodon: {
		supported: false,
		name: "Mastodon",
		logo: MastodonIcon,
		color: "dark",
	},
	medium: {
		supported: false,
		name: "Medium",
		logo: MediumIcon,
		color: "dark/white",
	},
	pinterest: {
		supported: false,
		name: "Pinterest",
		logo: PinterestIcon,
		color: "red",
	},
	reddit: {
		supported: false,
		name: "Reddit",
		logo: RedditIcon,
		color: "orange",
	},
	slack: {
		supported: false,
		name: "Slack",
		logo: SlackIcon,
		color: "purple",
	},
	snapchat: {
		supported: false,
		name: "Snapchat",
		logo: SnapchatIcon,
		color: "yellow",
	},
	telegram: {
		supported: false,
		name: "Telegram",
		logo: TelegramIcon,
		color: "sky",
	},
	tumblr: {
		supported: false,
		name: "Tumblr",
		logo: TumblrIcon,
		color: "dark",
	},
	vimeo: {
		supported: false,
		name: "Vimeo",
		logo: VimeoIcon,
		color: "cyan",
	},
} as const;
